### PR TITLE
More phase non-provability checks

### PR DESCRIPTION
**Pull request by olaure01**

### CODE REVIEW

**Comment by etiennecallies** [comment]
If it fixes some bug, please reproduce it in a test. Just add some json here https://github.com/etiennecallies/click-and-collect/blob/master/test/api_test_data.json#L1154

**Comment by olaure01** [comment]
Not really a bug: checks are known not to be exhaustive, but more checks means less false positive, that's all.
I can add some tests to reflect old false positive which are now detected as negative if useful, but it is an endless process anyway.

**Comment by etiennecallies** [comment]
I think it's a good idea to add tests whenever possible for these reasons:
- make the reviewer understand what concrete case the PR is resolving/improving
- ensure it actually works
- give more insurance that we don't break the code in future refactoring. But I agree it will never be 100% insurance.

When I have time, I will try to make tests run on each PR.
Thanks!

**Comment by olaure01** [comment]
Done

**Comment by etiennecallies** [comment]
Thanks @olaure01 !

**Pull request merged**
