### PR TITLE
Add cut front and back

### PR DESCRIPTION
**Pull request by etiennecallies**
@olaure01 I saw you had different ideas for Coq and Cut_proof.

Except Coq export, everything should work on preprod: https://linearon.modusponens.dev/

### CODE REVIEW

**Comment by olaure01** [comment]
@etiennecallies I started implementing what is described in the [enhancement proposal](https://github.com/etiennecallies/click-and-collect/wiki/Enhancement-Proposals#cut-rule) but I need more time.
I will try to push quickly a direct preliminary version (with only the axiomatic approach) for defining and testing the export.

**Comment by olaure01** [comment]
First test remarks:
- in the pop-up window for cut formula: accept "Enter" to send the formula (currently it is necessary to click on `Cut`)
- in the pop-up window for cut formula: clear history from one call to the next
- add the cut rule in the list of derivation rules

**Comment by etiennecallies** [comment]
> First test remarks:
> 
> * in the pop-up window for cut formula: accept "Enter" to send the formula (currently it is necessary to click on `Cut`)

Done

> * in the pop-up window for cut formula: clear history from one call to the next

I made auto-selection on previously submitted cut formula, so that you can type new one or modify previous one.

> * add the cut rule in the list of derivation rules

Yes, done.

**Comment by etiennecallies** [comment]
> @etiennecallies I started implementing what is described in the [enhancement proposal](https://github.com/etiennecallies/click-and-collect/wiki/Enhancement-Proposals#cut-rule) but I need more time.
> I will try to push quickly a direct preliminary version (with only the axiomatic approach) for defining and testing the export.

No problem.

**Comment by etiennecallies** [comment]
Many thanks @olaure01 ! For me this is ready for merging.

**Comment by olaure01** [comment]
Fixes #12

**Pull request merged**
