### PR TITLE
[export] add ascii and utf8

### PR DESCRIPTION
**Pull request by olaure01**
OCaml side only. Interface is missing.

### CODE REVIEW

**Comment by etiennecallies** [comment]
Can be tested on [preprod](https://linearon.modusponens.dev/) (under LaTeX button)

**Comment by olaure01** [comment]
A few suggestions:
- use the previous photo (png) icon or something like this one: Proof Drawing rather than `LaTeX`
- rephrase help on main page as: "To generate a drawing of your proof click on `Proof Drawing` button. You will then be able to select among: LaTeX source, PDF export, PNG image, Ascii or UTF8 representation."
- In the opened window:
  - PDF LaTeX converted in PDF format
  - PNG LaTeX converted in PNG format
  - Ascii Text representation using ASCII characters only
  - UTF-8 Text representation using UTF-8 characters (better displayed with fixed width fonts)
  - consider the explicit/implicit option as for auto-reverse:
      `explicit exchange (i) (o-)`
  with help over `(i)`: 
  either a short "Draw explicit exchange rules"
   or some "Learn about explicit exchange option` and then open a window by clicking with "By default, no exchange rule will appear in the export: the output will be displayed as in the interface (snapshot). With explicit exchange activated, required exchanges will appear in the export, to get derivation rules applied strictly through the proof."

**Comment by etiennecallies** [comment]
Good suggestions, deployed on preprod.

**Comment by etiennecallies** [comment]
To avoid conflicts it's easier for me to merge. I would be happy to improve the export popup later on.

**Pull request merged**
