### PR TITLE
Auto-prover with non-recursive notations

### PR DESCRIPTION
**Pull request by etiennecallies**

### CODE REVIEW

**Comment by etiennecallies** [comment]
Works on preprod: https://linearon.modusponens.dev/?s=A&n=A%2CB%7CB&n=B%2C%3F1

**Review by olaure01 — APPROVED** [review]
It looks great!
Maybe update help about orange ⊢.
I was wondering whether it could be interesting to consider the following approach to cyclic notations: spend 2s searching for a proof without using these cyclic notations at all (just like now), spend 0.5s after a single round of unfolding of each of them, spend 0.5s for a depth 2 unfolding, then fail.

**Comment by etiennecallies** [comment]
> Maybe update help about orange ⊢.

I precised `recursive` in Help. You can suggest an edit if you see of a better way to say it.

**Comment by etiennecallies** [comment]
> I was wondering whether it could be interesting to consider the following approach to cyclic notations: spend 2s searching for a proof without using these cyclic notations at all (just like now), spend 0.5s after a single round of unfolding of each of them, spend 0.5s for a depth 2 unfolding, then fail.

https://github.com/etiennecallies/click-and-collect/issues/128

**Comment by olaure01** [comment]
> > Maybe update help about orange ⊢.
> 
> I precised `recursive` in Help. You can suggest an edit if you see of a better way to say it.

I missed it, sorry. Perfect.

**Pull request merged**
