### PR TITLE
Apply reversible first

### PR DESCRIPTION
**Pull request by etiennecallies**
Specs:
> click on a reversible connective (including ! in ?-context): applies the corresponding rule and do the corresponding reversing in  the above proof (may require some axiom expansion steps, and modifying hypotheses as well)

Can not apply on preprod now, due to maintenance.

### CODE REVIEW

**Comment by olaure01** [comment]
When clicking on a `&` connective in the conclusion of a `&` rule with twice the same premise, a strange proof-copying is involved.
Try clicking on the lower `&` connective in [this proof](https://ccll.linear-logic.org/?s=A%7CB%2CC%26C&proof_transformation=1&p=XQAAgAD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwA9iIoHZADSvL4AO2WnajJ4cSZ3uOM1Jm1oajsTKyplYJSCC8%2FPl15o2cdBQSb4YZPyMmHFofG192Ts6h2cAkDG3MP7wzSWx0VvLk6RTjzOzUmuEz25UYjhAUQ4FlCJQEVYZ2m2HE8V%2FpdJM24GDpqFDW2UEbFS5rBX5yhyu2ru%2BwO9Up6jQRUOsvoamNy8kfPOkfJ1yFK40oPCRqN72w4FaE8cy%2FfSa0JoKyRyhNJn6ooCdMWQ2C97Zv%2FrCKvH).

**Comment by etiennecallies** [comment]
> When clicking on a `&` connective in the conclusion of a `&` rule with twice the same premise, a strange proof-copying is involved.
> Try clicking on the lower `&` connective in [this proof](https://ccll.linear-logic.org/?s=A%7CB%2CC%26C&proof_transformation=1&p=XQAAgAD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwA9iIoHZADSvL4AO2WnajJ4cSZ3uOM1Jm1oajsTKyplYJSCC8%2FPl15o2cdBQSb4YZPyMmHFofG192Ts6h2cAkDG3MP7wzSWx0VvLk6RTjzOzUmuEz25UYjhAUQ4FlCJQEVYZ2m2HE8V%2FpdJM24GDpqFDW2UEbFS5rBX5yhyu2ru%2BwO9Up6jQRUOsvoamNy8kfPOkfJ1yFK40oPCRqN72w4FaE8cy%2FfSa0JoKyRyhNJn6ooCdMWQ2C97Zv%2FrCKvH).

Good catch 👍🏻

**Comment by olaure01** [comment]
Double click reverses hereditarily the reversible sub-formulas?
Dedicated button for full reversing of all concluding reversible formulas (including reversible sub-formulas)?

**Comment by olaure01** [comment]
Trying to reverse a `!` with not a `?`-context generates an error message `Can not apply 'promotion' rule: the context must contain formulas starting by '?' only.`
It is OK, but just to mention that an alternative would be not to activate reversibility of `!` in such a situation. Not sure what is the best to do.

**Comment by etiennecallies** [comment]
I opened #163 for the enhancements of this feature.

**Pull request merged**
